# Generated by Django 3.2.5 on 2021-12-09 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('post', models.TextField()),
                ('Image', models.ImageField(blank=True, upload_to='pics')),
                ('Video', models.FileField(blank=True, upload_to='vids')),
                ('audio', models.FileField(blank=True, upload_to='auds')),
                ('documents', models.FileField(blank=True, upload_to='docs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
