# Generated by Django 3.2.5 on 2021-11-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='Image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='Video',
            field=models.FileField(blank=True, upload_to='vids'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='audio',
            field=models.FileField(blank=True, upload_to='auds'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='documents',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
    ]
