# Generated by Django 3.2.5 on 2021-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0003_alter_storage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='Video',
            field=models.FileField(upload_to='vids'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='audio',
            field=models.FileField(upload_to='auds'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='documents',
            field=models.FileField(upload_to='docs'),
        ),
    ]
