# Generated by Django 3.2.5 on 2021-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0004_auto_20211123_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='Video',
            field=models.FileField(blank=True, upload_to='vids'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='audio',
            field=models.FileField(blank=True, upload_to='auds'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='documents',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
    ]
