# Generated by Django 3.2.5 on 2021-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0005_auto_20211123_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='Image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
